### ISSUE TITLE
Both the master and solution branches have the same code.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/react-create-element-lab#4]
When you open the lab it is already filled in with the solution.

https://github.com/learn-co-curriculum/react-create-element-lab/pull/3

This pull request from cernanb fixes the code to how the lab should be on the master branch.

**Comment by pickledyamsman** [comment]
cc @aturkewi @AnnJohn

**Comment by AnnJohn** [comment]
thanks- merged the PR.
